"""Langfuse Prompt Provider Adapter.

Conforms to ADR-014 and ADR-017:
    - When Langfuse is reachable, retrieves versioned prompts and configs from Langfuse Cloud.
    - Guaranteed Availability: When Langfuse is offline, unreachable, or fails, falls back immediately
      to the injected JsonPromptProvider with zero pipeline downtime.
    - Tracks active prompt object/version for linking to LLM generation observations.
    - Uses canonical PROMPT_REGISTRY to eliminate duplicated hardcoded prompt names.
"""

from __future__ import annotations

import logging
from http import HTTPStatus
from typing import Any

from langfuse.api.core import ApiError

from cresmo.application.ports import PromptProviderPort
from cresmo.domain.value_objects import ChannelName
from cresmo.infrastructure.adapters.prompts.registry import (
    PROMPT_REGISTRY,
    PromptKey,
)
from cresmo.infrastructure.config import CresmoSettings

logger = logging.getLogger(__name__)


def _handle_api_error(exc: ApiError, prompt_name: str, label: str) -> None:
    """Log structured warning for Langfuse API errors."""
    if exc.status_code == HTTPStatus.NOT_FOUND:
        logger.warning(
            "[LangfusePromptProvider] Prompt '%s' not found in Langfuse (404). "
            "Create it in Langfuse Cloud or use label='%s'. Using local fallback.",
            prompt_name,
            label,
        )
    else:
        logger.warning(
            "[LangfusePromptProvider] Langfuse API error fetching '%s' (HTTP %s: %s). "
            "Using local fallback.",
            prompt_name,
            exc.status_code,
            exc.body,
        )


def _extract_prompt_messages(
    compiled_messages: Any,
    fallback_system_instruction: str,
    fallback_user_prompt: str,
    kwargs: dict[str, Any],
) -> tuple[str, str]:
    """Extract system instruction and user prompt from compiled Langfuse chat messages."""
    if not isinstance(compiled_messages, list):
        return fallback_system_instruction, fallback_user_prompt

    system_instruction = fallback_system_instruction
    user_prompt = fallback_user_prompt
    for msg in compiled_messages:
        if not isinstance(msg, dict):
            continue
        role = msg.get("role")
        content = msg.get("content")
        if content is None:
            continue
        if role == "system":
            system_instruction = str(content)
        elif role == "user":
            user_prompt = str(content)

    for key, value in kwargs.items():
        user_prompt = user_prompt.replace(f"{{{key}}}", str(value))
        system_instruction = system_instruction.replace(f"{{{key}}}", str(value))

    return system_instruction, user_prompt


class LangfusePromptProvider(PromptProviderPort):
    """Hexagonal Adapter providing prompts via Langfuse with guaranteed local fallback.

    Conforms to ADR-014 and ADR-017:
        - When Langfuse is reachable, retrieves versioned prompts and configs.
        - Guaranteed Availability: When Langfuse is offline or fails, falls back immediately
          to the injected JsonPromptProvider with zero pipeline downtime.
        - Tracks active prompt object/version for linking to LLM generation observations.
    """

    def __init__(
        self,
        langfuse_client: Any | None,
        fallback_provider: PromptProviderPort,
        label: str = CresmoSettings.DEFAULT_LANGFUSE_PROMPT_LABEL,
    ) -> None:
        """Initialize Langfuse prompt provider.

        Args:
            langfuse_client: Optional active Langfuse client instance.
            fallback_provider: Injected local PromptProviderPort fallback.
            label: Active prompt version label in Langfuse (e.g. 'production', 'staging').
        """
        self._client = langfuse_client
        self._fallback = fallback_provider
        self._label = label
        self._last_prompt_versions: dict[str, Any] = {}

    def get_last_prompt_version(self, prompt_name: str) -> Any | None:
        """Return the last resolved version for a given prompt identifier."""
        return self._last_prompt_versions.get(prompt_name)

    def _resolve_chat_prompt(
        self,
        prompt_name: str,
        fallback_system_instruction: str,
        fallback_user_prompt: str,
        **kwargs: Any,
    ) -> tuple[str, str]:
        """Attempt to fetch and compile Chat-Native prompt from Langfuse with seamless fallback.

        Conforms to ADR-010, ADR-017, and ADR-022:
            - Fetches strictly Chat Prompts (`type="chat"`).
            - Unpacks messages: `role="system"` -> system_instruction, `role="user"` -> user_prompt.
            - Guaranteed Availability: On error or client=None, falls back to injected fallback provider.

        Args:
            prompt_name: Identifier for the prompt registered in Langfuse.
            fallback_system_instruction: Ground-truth system instruction generated by fallback provider.
            fallback_user_prompt: Ground-truth user prompt template generated by fallback provider.
            **kwargs: Template variable substitutions.

        Returns:
            Tuple containing (system_instruction, user_prompt).
        """
        if self._client is None:
            return fallback_system_instruction, fallback_user_prompt

        try:
            prompt = self._client.get_prompt(
                prompt_name,
                label=self._label,
                type="chat",
            )
            if hasattr(prompt, "version"):
                self._last_prompt_versions[prompt_name] = prompt.version

            if hasattr(prompt, "compile"):
                compiled_messages = prompt.compile(**kwargs)
                return _extract_prompt_messages(
                    compiled_messages,
                    fallback_system_instruction,
                    fallback_user_prompt,
                    kwargs,
                )

            return fallback_system_instruction, fallback_user_prompt
        except ApiError as exc:
            _handle_api_error(exc, prompt_name, self._label)
            return fallback_system_instruction, fallback_user_prompt
        except Exception as exc:  # noqa: BLE001 — transient infra failure (timeout, auth, etc.)
            logger.warning(
                "[LangfusePromptProvider] Transient error fetching prompt '%s' (%s: %s). "
                "Using local fallback.",
                prompt_name,
                type(exc).__name__,
                exc,
            )
            return fallback_system_instruction, fallback_user_prompt

    def get_prompt(
        self,
        key: PromptKey,
        **context: Any,
    ) -> tuple[str, str]:
        """Dispatch prompt formatting via Langfuse Cloud with guaranteed local fallback.

        Conforms to ADR-014 and ADR-017:
            - Fetches versioned Chat Prompt from Langfuse Cloud when client is active.
            - Guaranteed Availability: Gracefully falls back to local provider on error or missing client.
            - Tracks resolved version for downstream generation observability.

        Args:
            key: Canonical PromptKey enum member.
            **context: Template variable substitutions.

        Returns:
            Tuple containing (system_instruction, user_prompt).
        """
        fallback_system_instruction, fallback_user_prompt = self._fallback.get_prompt(key, **context)
        prompt_descriptor = PROMPT_REGISTRY.get(key)
        if prompt_descriptor is None:
            return fallback_system_instruction, fallback_user_prompt

        # Normalize ChannelName to str for template compilation if present
        compile_context = dict(context)
        if "channel_name" in compile_context:
            channel_name = compile_context["channel_name"]
            compile_context["channel_name"] = (
                channel_name.value if isinstance(channel_name, ChannelName) else str(channel_name)
            )

        return self._resolve_chat_prompt(
            prompt_name=prompt_descriptor.langfuse_name,
            fallback_system_instruction=fallback_system_instruction,
            fallback_user_prompt=fallback_user_prompt,
            **compile_context,
        )
