"""Langfuse Prompt Provider Adapter.

Conforms to ADR-014 and ADR-017:
    - When Langfuse is reachable, retrieves versioned prompts and configs from Langfuse Cloud.
    - Guaranteed Availability: When Langfuse is offline, unreachable, or fails, falls back immediately
      to the injected JsonPromptProvider with zero pipeline downtime.
    - Tracks active prompt object/version for linking to LLM generation observations.
    - Uses canonical PROMPT_REGISTRY to eliminate duplicated hardcoded prompt names.
"""

from __future__ import annotations

import logging
from typing import Any

from cresmo.application.ports import PromptProviderPort
from cresmo.domain.value_objects import ChannelName
from cresmo.infrastructure.adapters.prompts.registry import (
    PROMPT_REGISTRY,
    PromptKey,
)

logger = logging.getLogger(__name__)


class LangfusePromptProvider(PromptProviderPort):
    """Hexagonal Adapter providing prompts via Langfuse with guaranteed local fallback.

    Conforms to ADR-014 and ADR-017:
        - When Langfuse is reachable, retrieves versioned prompts and configs.
        - Guaranteed Availability: When Langfuse is offline or fails, falls back immediately
          to the injected JsonPromptProvider with zero pipeline downtime.
        - Tracks active prompt object/version for linking to LLM generation observations.
    """

    def __init__(
        self,
        langfuse_client: Any | None,
        fallback_provider: PromptProviderPort,
        label: str = "production",
    ) -> None:
        """Initialize Langfuse prompt provider.

        Args:
            langfuse_client: Optional active Langfuse client instance.
            fallback_provider: Injected local PromptProviderPort fallback.
            label: Active prompt version label in Langfuse (e.g. 'production', 'staging').
        """
        self._client = langfuse_client
        self._fallback = fallback_provider
        self._label = label
        self._last_prompt_versions: dict[str, Any] = {}

    def get_last_prompt_version(self, prompt_name: str) -> Any | None:
        """Return the last resolved version for a given prompt identifier."""
        return self._last_prompt_versions.get(prompt_name)

    def _resolve_chat_prompt(
        self,
        prompt_name: str,
        fallback_sys: str,
        fallback_user: str,
        **kwargs: Any,
    ) -> tuple[str, str]:
        """Attempt to fetch and compile Chat-Native prompt from Langfuse with seamless fallback.

        Conforms to ADR-010, ADR-017, and ADR-022:
            - Fetches strictly Chat Prompts (`type="chat"`).
            - Unpacks messages: `role="system"` -> system_instruction, `role="user"` -> user_prompt.
            - Guaranteed Availability: On error or client=None, falls back to injected fallback provider.

        Args:
            prompt_name: Identifier for the prompt registered in Langfuse.
            fallback_sys: Ground-truth system instruction generated by fallback provider.
            fallback_user: Ground-truth user prompt template generated by fallback provider.
            **kwargs: Template variable substitutions.

        Returns:
            Tuple containing (system_instruction, user_prompt).
        """
        if self._client is None:
            return fallback_sys, fallback_user

        try:
            prompt = self._client.get_prompt(
                prompt_name,
                label=self._label,
                type="chat",
            )
            if hasattr(prompt, "version"):
                self._last_prompt_versions[prompt_name] = prompt.version

            if hasattr(prompt, "compile"):
                compiled_messages = prompt.compile(**kwargs)
                sys_inst = fallback_sys
                user_p = fallback_user
                if isinstance(compiled_messages, list):
                    for msg in compiled_messages:
                        if isinstance(msg, dict):
                            role = msg.get("role")
                            content = msg.get("content")
                            if role == "system" and content is not None:
                                sys_inst = str(content)
                            elif role == "user" and content is not None:
                                user_p = str(content)
                    return sys_inst, user_p

            return fallback_sys, fallback_user
        except Exception as exc:  # noqa: BLE001
            logger.debug(
                "[LangfusePromptProvider] Prompt '%s' fetch skipped (%s), using local fallback",
                prompt_name,
                exc,
            )
            return fallback_sys, fallback_user

    def get_gap_filler_prompt(
        self,
        pass_num: int,
        total_passes: int,
        channel_name: ChannelName,
        file_name: str,
        raw_text: str,
        current_text: str | None = None,
    ) -> tuple[str, str]:
        """Format (system_instruction, user_prompt) via Langfuse with guaranteed fallback."""
        fallback_sys, fallback_user = self._fallback.get_gap_filler_prompt(
            pass_num=pass_num,
            total_passes=total_passes,
            channel_name=channel_name,
            file_name=file_name,
            raw_text=raw_text,
            current_text=current_text,
        )
        key = PromptKey.GAP_FILLER_PASS1 if pass_num == 1 else PromptKey.GAP_FILLER_PASS_SUBSEQUENT
        prompt_name = PROMPT_REGISTRY[key].langfuse_name
        return self._resolve_chat_prompt(
            prompt_name=prompt_name,
            fallback_sys=fallback_sys,
            fallback_user=fallback_user,
            pass_num=pass_num,
            total_passes=total_passes,
            channel_name=channel_name,
            file_name=file_name,
            raw_text=raw_text,
            current_text=current_text or "",
        )

    def get_long_expander_prompt(
        self,
        compendium_body: str,
        complementary_info: str,
    ) -> tuple[str, str]:
        """Format (system_instruction, user_prompt) for longitudinal expansion via Langfuse."""
        fallback_sys, fallback_user = self._fallback.get_long_expander_prompt(
            compendium_body=compendium_body,
            complementary_info=complementary_info,
        )
        prompt_name = PROMPT_REGISTRY[PromptKey.LONG_EXPANDER].langfuse_name
        return self._resolve_chat_prompt(
            prompt_name=prompt_name,
            fallback_sys=fallback_sys,
            fallback_user=fallback_user,
            compendium_body=compendium_body,
            complementary_info=complementary_info,
        )

    def get_wide_expander_prompt(
        self,
        current_text: str,
    ) -> tuple[str, str]:
        """Format (system_instruction, user_prompt) for synchronic wide expansion via Langfuse."""
        fallback_sys, fallback_user = self._fallback.get_wide_expander_prompt(
            current_text=current_text
        )
        prompt_name = PROMPT_REGISTRY[PromptKey.WIDE_EXPANDER].langfuse_name
        return self._resolve_chat_prompt(
            prompt_name=prompt_name,
            fallback_sys=fallback_sys,
            fallback_user=fallback_user,
            current_text=current_text,
        )

    def get_inventory_prompt(
        self,
        compendium_title: str,
        channel_name: ChannelName,
        compendium_body: str,
    ) -> tuple[str, str]:
        """Format (system_instruction, user_prompt) for atomic inventory extraction via Langfuse."""
        fallback_sys, fallback_user = self._fallback.get_inventory_prompt(
            compendium_title=compendium_title,
            channel_name=channel_name,
            compendium_body=compendium_body,
        )
        prompt_name = PROMPT_REGISTRY[PromptKey.ATOMIC_INVENTORY].langfuse_name
        return self._resolve_chat_prompt(
            prompt_name=prompt_name,
            fallback_sys=fallback_sys,
            fallback_user=fallback_user,
            compendium_title=compendium_title,
            channel_name=channel_name,
            compendium_body=compendium_body,
        )

    def get_judge_inventory_prompt(
        self,
        compendium_title: str,
        channel_name: ChannelName | str,
        compendium_body: str,
        inventory_json: str,
    ) -> tuple[str, str]:
        """Format (system_instruction, user_prompt) for atomic inventory judge via Langfuse."""
        fallback_sys, fallback_user = self._fallback.get_judge_inventory_prompt(
            compendium_title=compendium_title,
            channel_name=channel_name,
            compendium_body=compendium_body,
            inventory_json=inventory_json,
        )
        prompt_name = PROMPT_REGISTRY[PromptKey.JUDGE_ATOMIC_INVENTORY].langfuse_name
        ch_str = channel_name.value if isinstance(channel_name, ChannelName) else channel_name
        return self._resolve_chat_prompt(
            prompt_name=prompt_name,
            fallback_sys=fallback_sys,
            fallback_user=fallback_user,
            compendium_title=compendium_title,
            channel_name=ch_str,
            compendium_body=compendium_body,
            inventory_json=inventory_json,
        )

    def get_batch_notes_prompt(
        self,
        compendium_title: str,
        channel_name: ChannelName,
        compendium_body: str,
        targets_json: str,
    ) -> tuple[str, str]:
        """Format (system_instruction, user_prompt) for atomic note batch synthesis via Langfuse."""
        fallback_sys, fallback_user = self._fallback.get_batch_notes_prompt(
            compendium_title=compendium_title,
            channel_name=channel_name,
            compendium_body=compendium_body,
            targets_json=targets_json,
        )
        prompt_name = PROMPT_REGISTRY[PromptKey.ATOMIC_BATCH].langfuse_name
        return self._resolve_chat_prompt(
            prompt_name=prompt_name,
            fallback_sys=fallback_sys,
            fallback_user=fallback_user,
            compendium_title=compendium_title,
            channel_name=channel_name,
            compendium_body=compendium_body,
            targets_json=targets_json,
        )

    def get_mocs_prompt(
        self,
        notes_json: str,
    ) -> tuple[str, str]:
        """Format (system_instruction, user_prompt) for MOC reconciliation via Langfuse."""
        fallback_sys, fallback_user = self._fallback.get_mocs_prompt(notes_json=notes_json)
        prompt_name = PROMPT_REGISTRY[PromptKey.RECONCILE_MOCS].langfuse_name
        return self._resolve_chat_prompt(
            prompt_name=prompt_name,
            fallback_sys=fallback_sys,
            fallback_user=fallback_user,
            notes_json=notes_json,
        )

    def get_raw_index_summary_prompt(
        self,
        video_title: str,
        transcript_excerpt: str,
        language: str = "Português do Brasil",
    ) -> tuple[str, str]:
        """Delegate raw index summary prompt formatting to local fallback."""
        return self._fallback.get_raw_index_summary_prompt(
            video_title=video_title,
            transcript_excerpt=transcript_excerpt,
            language=language,
        )

    def get_raw_index_concepts_prompt(
        self,
        video_title: str,
        transcript_excerpt: str,
        language: str = "Português do Brasil",
    ) -> tuple[str, str]:
        """Delegate raw index concepts prompt formatting to local fallback."""
        return self._fallback.get_raw_index_concepts_prompt(
            video_title=video_title,
            transcript_excerpt=transcript_excerpt,
            language=language,
        )

    def get_raw_index_concepts_rewrite_prompt(
        self,
        previous_output: str,
        language: str = "Português do Brasil",
    ) -> str:
        """Delegate raw index concepts rewrite prompt formatting to local fallback."""
        return self._fallback.get_raw_index_concepts_rewrite_prompt(
            previous_output=previous_output,
            language=language,
        )

    def get_raw_index_synthesis_prompt(
        self,
        video_title: str,
        summary: str,
        language: str = "Português do Brasil",
    ) -> tuple[str, str]:
        """Delegate raw index synthesis prompt formatting to local fallback."""
        return self._fallback.get_raw_index_synthesis_prompt(
            video_title=video_title,
            summary=summary,
            language=language,
        )

    def get_judge_raw_index_summary_prompt(
        self,
        video_title: str,
        transcript_excerpt: str,
        summary: str,
        language: str = "Português do Brasil",
    ) -> tuple[str, str]:
        """Delegate judge summary prompt formatting to local fallback."""
        return self._fallback.get_judge_raw_index_summary_prompt(
            video_title=video_title,
            transcript_excerpt=transcript_excerpt,
            summary=summary,
            language=language,
        )

    def get_judge_raw_index_concepts_prompt(
        self,
        video_title: str,
        transcript_excerpt: str,
        concepts: str,
        language: str = "Português do Brasil",
    ) -> tuple[str, str]:
        """Delegate judge concepts prompt formatting to local fallback."""
        return self._fallback.get_judge_raw_index_concepts_prompt(
            video_title=video_title,
            transcript_excerpt=transcript_excerpt,
            concepts=concepts,
            language=language,
        )

    def get_judge_raw_index_synthesis_prompt(
        self,
        video_title: str,
        transcript_excerpt: str,
        synthesis: str,
        language: str = "Português do Brasil",
    ) -> tuple[str, str]:
        """Delegate judge synthesis prompt formatting to local fallback."""
        return self._fallback.get_judge_raw_index_synthesis_prompt(
            video_title=video_title,
            transcript_excerpt=transcript_excerpt,
            synthesis=synthesis,
            language=language,
        )
