"""Hermetic Unit Tests for SourceTranscript, CandidateText, and Typed Verdict Value Objects.

Conforms to:
    - ADR-031: Standardized StageConfig, SourceTranscript, CandidateText, and Closed-Loop Reflection Quality Fabric
    - SPEC-014: Standardized Stage Execution and Decision-Model Quality Fabric Specification
"""

from __future__ import annotations

import datetime

import pytest

from cresmo.domain.entities import SourceTranscript
from cresmo.domain.exceptions import DomainValidationError
from cresmo.domain.value_objects import (
    CandidateText,
    ChannelId,
    ChannelName,
    ContentId,
    CriterionScore,
    JudgeCriterion,
    JudgeEvaluation,
    TypedVerdict,
    VerdictType,
)


class TestSourceTranscript:
    """Test suite for SourceTranscript domain aggregate/VO."""

    def test_valid_source_transcript_instantiation(self) -> None:
        cid = ContentId("video_123")
        pub = datetime.date(2026, 1, 15)
        transcript = SourceTranscript(
            content_id=cid,
            channel_name=ChannelName("Test Channel"),
            body="Continuous raw or source transcript text.",
            title="Introduction to Socio-Technical Systems",
            publication_date=pub,
        )
        assert transcript.content.id == cid
        assert transcript.channel.name == "Test Channel"
        assert transcript.content.body == "Continuous raw or source transcript text."
        assert transcript.content.title == "Introduction to Socio-Technical Systems"
        assert transcript.provenance.publication_date == pub

    def test_source_transcript_string_coercion(self) -> None:
        transcript = SourceTranscript(
            content_id=ContentId("video_456"),
            channel_name="Raw Channel String",
            body="Sample body content",
            channel_id="UC1234567890123456789012",
        )
        assert transcript.channel.name == "Raw Channel String"
        assert isinstance(transcript.channel.id, ChannelId)
        assert transcript.channel.id == ChannelId("UC1234567890123456789012")

    def test_source_transcript_empty_body_raises(self) -> None:
        with pytest.raises(DomainValidationError, match="body cannot be empty"):
            SourceTranscript(
                content_id=ContentId("video_empty"),
                channel_name=ChannelName("Channel"),
                body="   \n\t  ",
            )


class TestCandidateText:
    """Test suite for CandidateText Value Object."""

    def test_valid_candidate_text(self) -> None:
        candidate = CandidateText(
            text="Cleaned fluid prose text generated by LLM.",
            stage_name="fluid_prose",
            metadata={"model": "gemini-2.5-pro", "temperature": 0.2},
        )
        assert candidate.text == "Cleaned fluid prose text generated by LLM."
        assert candidate.stage_name == "fluid_prose"
        assert candidate.metadata["model"] == "gemini-2.5-pro"

    def test_candidate_text_empty_raises(self) -> None:
        with pytest.raises(DomainValidationError, match="cannot be empty"):
            CandidateText(text="   ", stage_name="fluid_prose")

    def test_candidate_text_empty_stage_raises(self) -> None:
        with pytest.raises(DomainValidationError, match="stage_name cannot be empty"):
            CandidateText(text="Some text", stage_name="")


class TestTypedVerdictAndEvaluationCritique:
    """Test suite for VerdictType, TypedVerdict, and JudgeEvaluation critique extraction."""

    def test_typed_verdict_noul(self) -> None:
        verdict = TypedVerdict(
            criterion=JudgeCriterion.ORALITY_REMOVAL,
            verdict_type=VerdictType.NOUL,
            passed=True,
            score=1.0,
            confidence=0.98,
            reasoning="All filler words eliminated.",
        )
        assert verdict.verdict_type == VerdictType.NOUL
        assert verdict.passed is True
        assert verdict.score == 1.0

    def test_typed_verdict_score_and_suggestion(self) -> None:
        verdict = TypedVerdict(
            criterion=JudgeCriterion.SEMANTIC_FAITHFULNESS,
            verdict_type=VerdictType.SCORE,
            passed=False,
            score=0.6,
            reasoning="Omitted discussion of second-order determinants.",
            improvement_suggestion="Re-include the Annales School causal structure.",
        )
        assert verdict.passed is False
        assert verdict.score == 0.6
        assert verdict.improvement_suggestion != ""

    def test_judge_evaluation_extract_critique_combines_failures(self) -> None:
        score1 = CriterionScore(
            criterion=JudgeCriterion.ORALITY_REMOVAL,
            score=1.0,
            passed=True,
            reasoning="Clean.",
        )
        score2 = CriterionScore(
            criterion=JudgeCriterion.NER_PRESERVATION,
            score=0.4,
            passed=False,
            reasoning="Distorted proper name 'Fernand Braudel' to 'Brodell'.",
            improvement_suggestion="Restore original French orthography 'Fernand Braudel'.",
        )
        score3 = CriterionScore(
            criterion=JudgeCriterion.STRUCTURAL_COMPLIANCE,
            score=0.0,
            passed=False,
            reasoning="Stray table detected.",
            improvement_suggestion="Convert Markdown table into continuous prose.",
        )
        evaluation = JudgeEvaluation(
            target_stage="fluid_prose",
            passed=False,
            overall_score=0.46,
            criteria_scores=(score1, score2, score3),
            provider="typesafe",
        )

        critique = evaluation.extract_critique()
        assert "ner_preservation" in critique
        assert "Fernand Braudel" in critique
        assert "structural_compliance" in critique
        assert "Stray table detected" in critique
        assert "Restore original French orthography" in critique
